### PR TITLE
port to topkg

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
I tried to add `-safe-string`, but this library is not `safe-string` clean (yet).

**Comment by hannesm** [comment]
any merge window for this? (according to GitHub statistics, @djs55 is in charge) ;)  otherwise it'll likely get bitrot..

**Comment by samoht** [comment]
Thanks! I'll make a new release shortly

**Comment by samoht** [comment]
Done: https://github.com/ocaml/opam-repository/pull/8415

**Comment by hannesm** [comment]
while the [documentation landing page](https://mirage.github.io/ocaml-tar/) looks allright, the module pages (e.g. [Tar](https://mirage.github.io/ocaml-tar/Tar.html)) have a rather colourful style.

**Comment by samoht** [comment]
Fixed

**Pull request merged**
