### PR TITLE
Doc fixes, build updates, lower-bound Cstruct on 6.0.0, fix, setup-ocaml

### PR DESCRIPTION
**Pull request by MisterDA**
I updated minor stuff, the documentation and the build system.
I noticed that recent Cstruct deprecated `Cstruct.len`, so updated that.
There's also a little change, I think the library shouldn't print to the standard output when extracting files.

### CODE REVIEW

**Review by dinosaure — APPROVED** [review]
LGTM! I will add `ocaml-ci` on this repository. Do you have any plans for `ocaml-tar`?

**Review by djs55 — APPROVED** [review]

**Comment by MisterDA** [comment]
> Do you have any plans for `ocaml-tar`?

Well I'm hacking something with it right now, if I can't do what I want with what's currently available I might add more code to ocaml-tar but I think everything's there.
If you were asking whether you should make a release or not, maybe give it a couple of days?

**Comment by dinosaure** [comment]
> If you were asking whether you should make a release or not, maybe give it a couple of days?

Just to know your plan :+1:, `ocaml-tar` is pretty-old and it can be interesting to update it - specially to mix it with `decompress` and support `*.tar.gz`. I can merge this PR and take care about a release of it :+1: - except if @djs55 want to care about that.

**Comment by MisterDA** [comment]
I just want to rename files in an archive streamed between two file descriptors :smile:

**Comment by djs55** [comment]
@dinosaure if you could handle the merge and release that would be great, thanks!

**Comment by MisterDA** [comment]
Just force-pushed minor doc fixes I spotted today. I think the PR's ready now, I have at least one other patch I want to submit when this is merged.

**Comment by dinosaure** [comment]
Rebased with #73

**Comment by dinosaure** [comment]
Failures are expected, I will do some small PR to fix the CI and do the release, thanks all! Ready to merge.

**Pull request merged**
